# Danh sách whitelist cho hệ thống phát hiện APT
# Các địa chỉ/domain trong danh sách này sẽ được bỏ qua khi phân tích

# Internal IP ranges (CIDR notation)
internal_ips:
  - "10.0.0.0/8"
  - "172.16.0.0/12"
  - "192.168.0.0/16"
  - "169.254.0.0/16"  # Link-local
  - "127.0.0.0/8"     # Localhost
  - "::1/128"         # IPv6 localhost
  - "fc00::/7"        # IPv6 unique local
  - "fe80::/10"       # IPv6 link-local

# Trusted domains - các domain hợp lệ thông thường
trusted_domains:
  - "google.com"
  - "googleapis.com"
  - "gstatic.com"
  - "microsoft.com"
  - "windowsupdate.com"
  - "apple.com"
  - "icloud.com"
  - "facebook.com"
  - "twitter.com"
  - "cloudflare.com"
  - "akamaiedge.net"
  - "amazonaws.com"
  - "azure.com"
  - "live.com"
  - "office.com"
  - "sharepoint.com"
  - "github.com"
  - "gitlab.com"
  - "stackoverflow.com"
  - "reddit.com"
  - "youtube.com"
  - "whatsapp.com"
  - "telegram.org"
  - "discord.com"
  - "slack.com"
  - "dropbox.com"
  - "drive.google.com"
  - "onedrive.com"

# Trusted CDNs và services
trusted_cdns:
  - "cloudfront.net"
  - "akamai.net"
  - "fastly.net"
  - "cdn.cloudflare.com"
  - "amazonaws.com"
  - "azureedge.net"
  - "googleusercontent.com"

# Trusted ports - các port thông thường
trusted_ports:
  - 80    # HTTP
  - 443   # HTTPS
  - 53    # DNS
  - 22    # SSH
  - 25    # SMTP
  - 110   # POP3
  - 143   # IMAP
  - 993   # IMAPS
  - 995   # POP3S
  - 587   # SMTP Submission
  - 21    # FTP
  - 23    # Telnet
  - 123   # NTP
  - 161   # SNMP
  - 389   # LDAP
  - 636   # LDAPS
  - 3389  # RDP

# Known benign user agents
benign_user_agents:
  - "Mozilla/5.0"
  - "Chrome/"
  - "Firefox/"
  - "Safari/"
  - "Edge/"
  - "Windows-Update-Agent"
  - "Microsoft-Delivery-Optimization"
  - "Apple-PubSub"

# Known JA3 fingerprints của phần mềm hợp lệ
trusted_ja3_hashes:
  - "6734f37431670b3ab4292b8f60f29984"  # Chrome Windows
  - "b32309a26951912be7dba376398abc3b"  # Firefox Windows
  - "c36fb4eb49b4b7b39b5723840b19d18b"  # Edge Windows
  - "6f8d64dc5c8b6b2a6e2d3a3c9e3e3a3e"  # Safari MacOS (example)

# Internal domains (nếu có)
internal_domains:
  - ".local"
  - ".internal"
  - ".corp"
  - ".localdomain"
  - "dc."
  - "ad."
  - "domain."

# Bypass rules for specific detection methods
detection_bypass:
  beaconing:
    # Các IP/domain được bỏ qua khi phát hiện beaconing
    exclude_ips: []
    exclude_domains: 
      - "windowsupdate.com"
      - "apple.com"
      - "google.com"
  
  dns_tunneling:
    # Các domain được bỏ qua khi phát hiện DNS tunneling
    exclude_domains:
      - "autodiscover.*"  # Microsoft Autodiscover
      - "_dmarc.*"        # DMARC records
      - "_domainkey.*"    # DKIM records
      - "_acme-challenge.*" # SSL certificates
    # Các TLD thông thường không bị coi là tunneling
    safe_tlds:
      - "com"
      - "org"
      - "net"
      - "edu"
      - "gov"
      - "io"
      - "co"

# Time windows for whitelist updates (giờ)
update_intervals:
  domain_whitelist: 168    # 1 tuần
  ip_whitelist: 24         # 1 ngày
  ja3_whitelist: 720       # 1 tháng

# Emergency override - tạm thời vô hiệu hóa whitelist
emergency_mode: false